### ISSUE TITLE
Could not find com.arthenica:ffmpeg-kit-full:5.1

### ISSUE THREAD

**Issue by erkihindo** [swimmingkiim/gify#3]
Hi,

Tried to use gify:

  gify: ^^1.0.9

Gave this error:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.arthenica:ffmpeg-kit-full:5.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/arthenica/ffmpeg-kit-full/5.1/ffmpeg-kit-full-5.1.pom
       - https://jcenter.bintray.com/com/arthenica/ffmpeg-kit-full/5.1/ffmpeg-kit-full-5.1.pom
       - https://storage.googleapis.com/download.flutter.io/com/arthenica/ffmpeg-kit-full/5.1/ffmpeg-kit-full-5.1.pom
       - https://repo.maven.apache.org/maven2/com/arthenica/ffmpeg-kit-full/5.1/ffmpeg-kit-full-5.1.pom
     Required by:
         project :app > project :ffmpeg_kit_flutter_full

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.5, on Microsoft Windows [Version 10.0.26120.3281], locale en-GB)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.3)
[√] Android Studio (version 2024.2)
[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

All dependencies:
```
dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  scoped_model: ^2.0.0
  shared_preferences: ^2.0.17  # storing stuff locally
  ndialog: 4.3.0 # confirm dialog on update tab TODO downgraded because it gave an error on specific flutter version
  youtube_player_flutter: ^9.0.1
  url_launcher: ^6.3.1 # opening links
  material_design_icons_flutter: ^7.0.7296 # nice icons
  package_info_plus: ^8.1.0 # Info about app version
  google_mobile_ads: 5.1.0
  bot_toast: ^4.1.3
  firebase_analytics: ^11.3.3
  auto_size_text: ^3.0.0
  flutter_local_notifications: ^18.0.1
  schedulers: ^1.0.1
  in_app_purchase: ^3.2.0
  dart_levenshtein: ^1.0.1
  sleek_circular_slider: ^2.0.1
  image_picker: ^1.0.4
  yaml: ^3.1.1
  flutter_sticky_header: ^0.7.0
  flutter_blurhash: ^0.8.2
  loading_indicator: ^3.0.3
  cupertino_stepper: ^0.2.1
  infinite_scroll_pagination: ^4.0.0 # community page
  like_button: ^2.0.5 # community page
  google_sign_in: ^6.1.5  # google sign in on community page
  bordered_text: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_chat_bubble: ^2.0.2
  flutter_emoji: ^2.4.0
  rive: ^0.13.20
  flutter_image_compress: ^2.3.0
  path_provider: ^2.0.11
  app_tracking_transparency: ^2.0.4
  super_tooltip: ^2.0.0
  retry: ^3.1.1
  sign_in_with_apple: ^6.1.3
  settings_ui: ^2.0.2
  percent_indicator: ^4.2.1
  material_floating_search_bar_2: ^0.5.0
  jiffy: ^6.2.1 # Date utils
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4 # upload videos
  flutter_swipecards: ^0.2.1
  animated_widgets: ^1.1.0
  badges: ^3.1.2 # notification when gotten likes or comments
  audioplayers: ^6.0.0 # sound effects
  share_plus: ^10.1.1
  expandable: ^5.0.1
  flutter_native_splash: ^2.1.6
  translator_plus: ^1.0.1 # temp translations until stuff is translated
  youtube_caption_scraper: ^0.2.0 # for generating link to subs translations
  language_tool: ^2.1.1
  confetti: ^0.8.0
  exif: ^3.1.4
  flip_card: ^0.7.0
  infinite_carousel: ^1.0.3
  table_calendar: # for calendar page
  wonderpush_flutter:  ^2.3.10 # notifications
  wonderpush_fcm_flutter: ^1.0.8
  flutter_form_builder: ^9.1.1 # calendar event creation
  form_builder_validators: ^10.0.1
  flutter_slidable: ^3.0.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  video_thumbnail: ^0.5.3 # For showing thumbnail in level practical part 2
  pinch_zoom: ^2.0.0 # For zooming in OnlineImage
  flutter_file_dialog: ^3.0.2 # for saving certification to local device
  app_links: ^6.1.1 # Possibly app links
  flutter_firebase_chat_core: ^1.6.7 # trainer chat
  flutter_chat_ui: ^1.6.12 # trainer chat
  firebase_auth: ^5.3.1
  open_filex: ^4.4.0
  wakelock_plus: ^1.2.10 # To keep trainer chat rooms open
  gma_mediation_unity: ^1.0.0
  ffmpeg_kit_flutter: 6.0.3
  gify: ^^1.0.9
```
